name: aws_client_generator
description: Code generator for package:aws_client
version: 0.2.0
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^6.11.0
  archive: ^3.6.1
  args: ^2.7.0
  collection: ^1.19.1
  dart_style: ^2.3.8
  html: ^0.15.5
  http: ^1.3.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  pool: ^1.5.1
  process_runner: ^4.2.0
  source_helper: ^1.3.5
  version: ^3.0.2
  yaml: ^3.1.3

dev_dependencies:
  lints: any
  build_runner: any
  build_verify: ^3.1.0
  json_serializable: ^6.9.4
  test: any
