name: shared_aws_api
description: Shared protocol implementation and utilities for generated AWS API clients.
version: 2.0.1

homepage: https://github.com/agilord/aws_client/tree/master/shared_aws_api

environment:
  sdk: '^3.7.0'

dependencies:
  crypto: ^3.0.6
  http: ^1.3.0
  meta: ^1.3.0
  xml:  ^6.5.0
  intl: ^0.19.0
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  lints: any
  test: any
